version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks: [laranet]

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks: [laranet]

  
  
  
    node:
    image: node:22        # was node:20
    container_name: vite
    working_dir: /var/www/html
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    networks: [laranet]


  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks: [laranet]

networks:
  laranet: {}

volumes:
  db-data: {}
