# Install PHP 8.3 + required extensions + Node 22 + Composer
[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",      # <-- FIX: composer lives under php83Packages
  "php83Extensions.intl",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.zip",
  "php83Extensions.exif",
  "php83Extensions.gd",
  "nodejs_22"
]

# Build your assets and prep storage
[phases.build]
cmds = [
  "composer install --no-dev --prefer-dist --optimize-autoloader",
  "npm ci",
  "npm run build",
  "php artisan storage:link || true"
]

# Serve Laravel on Railway's $PORT and run migrations on boot
[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT public/index.php"
